name: Tests

on: [push]

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv==2020.8.13
          pipenv install --system --dev

      - name: Test
        run: |
          ./test
